/**
 * User role enumeration for the BarakahLink platform.
 * 
 * Defines the three primary user types and their access levels:
 * - 'donor': Organizations or individuals who contribute food donations
 * - 'recipient': Community members who claim and pick up food donations
 * - 'guest': Unauthenticated users with limited platform access
 */
export type UserRole = 'donor' | 'recipient' | 'guest';

/**
 * Core data structure representing a food donation listing.
 * 
 * This interface defines all properties required to create, display, and manage
 * food drop listings in the BarakahLink platform. It encompasses donor information,
 * food details, location data, availability windows, and reservation status.
 * 
 * Key Components:
 * - Identification: Unique identifiers for the drop and donor
 * - Food Information: Title, description, quantity, and AI-generated metadata
 * - Location: Address and geographic coordinates for mapping
 * - Timing: Availability window with start and end timestamps
 * - Status: Current state of the donation (available, claimed, expired)
 * - Reservation: Optional recipient information when claimed
 * 
 * @interface FoodDrop
 */
export interface FoodDrop {
  /**
   * Unique identifier for this food drop listing.
   * Used for database operations, reservations, and tracking.
   */
  id: string;

  /**
   * Unique identifier for the donor who created this listing.
   * Links the food drop to a specific donor account for management and history.
   */
  donorId: string;

  /**
   * Display name of the donor organization or individual.
   * Shown to recipients to identify the source of the donation.
   * 
   * @example 'Kitchener Market Bakery', 'Green Gardens Farm'
   */
  donorName: string;

  /**
   * Contact phone number for the donor.
   * Used by recipients to coordinate pickup details or ask questions.
   * 
   * @example '519-555-0101'
   */
  donorPhone: string;

  /**
   * Short, descriptive title for the food donation.
   * Provides recipients with an immediate understanding of what's available.
   * 
   * @example 'Fresh Sourdough Loaves', 'Individual Pasta Meals'
   */
  title: string;

  /**
   * Detailed description of the food donation.
   * May include preparation details, storage instructions, dietary information,
   * or any other relevant details about the food.
   * 
   * This field is analyzed by AI for content moderation and tag generation.
   * 
   * @example '10 loaves of fresh sourdough baked this morning. Must go today!'
   */
  description: string;

  /**
   * Quantity of food available in this donation.
   * Can be specified in any unit (servings, kilograms, items, etc.).
   * 
   * @example '10 loaves', '15 portions', '5 kg'
   */
  quantity: string;

  /**
   * Street address where the food can be picked up.
   * Should be a complete, accurate address for recipient navigation.
   * 
   * @example '300 King St E', '75 King St S'
   */
  pickupAddress: string;

  /**
   * City where the pickup location is situated.
   * Used for filtering and organizing drops by geographic area.
   * 
   * @example 'Kitchener', 'Waterloo', 'Cambridge'
   */
  city: string;

  /**
   * Latitude coordinate of the pickup location.
   * Used for map display and distance calculations.
   * 
   * @example 43.4497
   */
  lat: number;

  /**
   * Longitude coordinate of the pickup location.
   * Used for map display and distance calculations.
   * 
   * @example -80.4855
   */
  lng: number;

  /**
   * ISO 8601 timestamp indicating when the food becomes available for pickup.
   * Recipients cannot claim the food before this time.
   * 
   * @example '2024-01-15T14:00:00.000Z'
   */
  pickupStartTime: string;

  /**
   * ISO 8601 timestamp indicating when the food is no longer available.
   * After this time, the drop should be marked as expired.
   * Used to ensure food safety and timely pickup.
   * 
   * @example '2024-01-15T18:00:00.000Z'
   */
  availableUntil: string;

  /**
   * Array of dietary and category tags for filtering and search.
   * Tags are typically generated by AI analysis but can also be manually added.
   * 
   * Common tags include dietary restrictions (Vegan, Halal, Gluten-Free),
   * food categories (Bakery, Hot Meal, Produce), and special attributes.
   * 
   * @example ['Vegan', 'Bakery'], ['Halal', 'Vegetarian', 'Hot Meal']
   */
  tags: string[];

  /**
   * Current lifecycle status of the food drop.
   * 
   * Status Values:
   * - 'available': Food is ready and unclaimed
   * - 'claimed': Reserved by a recipient, pending pickup
   * - 'expired': Past the availableUntil time or manually expired
   */
  status: 'available' | 'claimed' | 'expired';

  /**
   * ISO 8601 timestamp of when this food drop was created.
   * Used for sorting, analytics, and donor activity tracking.
   * 
   * @example '2024-01-15T13:30:00.000Z'
   */
  createdAt: string;

  /**
   * AI-generated summary of the food donation.
   * Provides a concise, recipient-friendly overview created by analyzing
   * the description and other metadata.
   * 
   * Optional field that may not be present on older drops or if AI analysis fails.
   * 
   * @example 'Fresh sourdough loaves from a local bakery, perfect for families.'
   */
  aiSummary?: string;

  /**
   * Recipient information when the drop has been claimed.
   * Contains contact details for pickup coordination.
   * 
   * Only present when status is 'claimed'. Used by donors to contact
   * recipients and coordinate pickup logistics.
   * 
   * @example { name: 'John Doe', phone: '519-555-0123' }
   */
  reservedBy?: {
    /**
     * Full name of the recipient who claimed the food.
     */
    name: string;

    /**
     * Contact phone number for the recipient.
     * Used by donors to coordinate pickup details.
     */
    phone: string;
  };
}

/**
 * Data structure representing an SMS message in the platform.
 * 
 * Used for SMS-based interactions with the BarakahLink platform,
 * allowing recipients without app access to interact via text messages.
 * Supports two-way communication with automated or manual responses.
 * 
 * @interface SMSMessage
 */
export interface SMSMessage {
  /**
   * Unique identifier for this SMS message.
   * Used for tracking, threading, and database operations.
   */
  id: string;

  /**
   * Phone number of the message sender.
   * Stored in a standardized format for consistent handling.
   * 
   * @example '+15195550123'
   */
  from: string;

  /**
   * The text content of the received SMS message.
   * Contains the recipient's query, request, or interaction with the platform.
   * 
   * @example 'Is the pasta still available?', 'I want to claim drop #123'
   */
  content: string;

  /**
   * Timestamp when the message was received.
   * Used for message ordering, threading, and analytics.
   * Stored as a Date object for easier manipulation and formatting.
   */
  timestamp: Date;

  /**
   * Optional response sent back to the message sender.
   * Can be an automated AI response or a manual reply from platform staff.
   * 
   * If undefined, the message has not yet been replied to.
   * 
   * @example 'Yes, the pasta is still available at 75 King St S until 6 PM.'
   */
  reply?: string;
}